#!/usr/bin/env python3
"""The consoles' look as data: colours, role colours and icons, read from the approved mockup.

The console mockup (docs/mockups/consoles.html) is the consoles' specification (CLAUDE.md 10:
an engine screen looks like its approved mockup). Its colour roles (`const C`), its icons
(`const ICONS`, 24-unit stroked SVG) and the role colours (shipkit.js `PALETTE.role`) are the
look the engine has to draw. Rather than a second hand-typed copy in Rust, this tool reads them
out of the mockup's own text and writes `data/ui/console_style.json`, which the engine compiles
in (openspec/changes/console-parity, design 3). `--check` fails when the file is not what the
mockup says, so the two cannot drift: change a colour or an icon in the mockup, rerun this.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MOCKUP = ROOT / "docs" / "mockups" / "consoles.html"
STATIONS = ROOT / "data" / "stations.json"
SHIPKIT = ROOT / "docs" / "mockups" / "lib" / "shipkit.js"
OUT = ROOT / "data" / "ui" / "console_style.json"


def block(text, start, open_ch="{", close_ch="}"):
    """The text between the bracket that opens at or after `start` and its partner."""
    i = text.index(open_ch, start)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == open_ch:
            depth += 1
        elif text[j] == close_ch:
            depth -= 1
            if depth == 0:
                return text[i + 1 : j]
    raise SystemExit("unbalanced block")


def colours(page):
    body = block(page, page.index("const C = {"))
    out = {}
    for k, v in re.findall(r'(\w+):\s*"(#[0-9a-fA-F]{6})"', body):
        out[k] = v.lower()
    return out


def icons(page):
    body = block(page, page.index("const ICONS = {"))
    out = {}
    for k, v in re.findall(r"^\s*(\w+):\s*'([^']*)',?\s*$", body, re.M):
        out[k] = v
    return out


def order_verbs(page):
    """The captain's orders, by station: [verb, icon] in the mockup's order (const ORDER_VERBS)."""
    body = block(page, page.index("const ORDER_VERBS = {"))
    out = {}
    for k, v in re.findall(r"^\s*(\w+):\s*\[(.*)\],?\s*$", body, re.M):
        out[k] = [[a, b] for a, b in re.findall(r'\["([^"]+)",\s*"([^"]+)"\]', v)]
    return out


def roles(kit):
    i = kit.index("const PALETTE = {")
    body = block(kit, kit.index("role: {", i))
    return {k: "#%06x" % int(v, 16) for k, v in re.findall(r"(\w+):\s*0x([0-9a-fA-F]{6})", body)}


def build():
    page = MOCKUP.read_text()
    kit = SHIPKIT.read_text()
    data = {
        "schema": "starcrew.console-style/1",
        "_doc": "Generated by tools/ui/console_style.py from docs/mockups/consoles.html (const C, const ICONS, const ORDER_VERBS) and "
        "docs/mockups/lib/shipkit.js (PALETTE.role). Do not edit: change the mockup and rerun the tool. Colours are "
        "sRGB hex; icons are SVG fragments on a 24-unit grid, stroked 2 units wide with round caps and joins. "
        "order_verbs are the captain's orders to each station, [verb, icon] (const ORDER_VERBS).",
        "colours": colours(page),
        "roles": roles(kit),
        "icons": icons(page),
        "order_verbs": order_verbs(page),
    }
    if len(data["icons"]) < 40 or len(data["colours"]) < 15 or len(data["roles"]) < 8 or len(data["order_verbs"]) < 4:
        raise SystemExit(f"parse came up short: {len(data['icons'])} icons, {len(data['colours'])} colours")
    # The captain's verbs are game data (data/stations.json, which sc-core validates orders against); the console
    # draws the mockup's. They are one list in two files, so the two are compared, not trusted (CLAUDE.md 6.6).
    game = json.loads(STATIONS.read_text())["orders"]
    if game != data["order_verbs"]:
        raise SystemExit(f"the mockup's ORDER_VERBS and {STATIONS.relative_to(ROOT)} 'orders' differ:\n"
                         f"  mockup: {data['order_verbs']}\n  data:   {game}")
    return json.dumps(data, indent=1, ensure_ascii=False) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if data/ui/console_style.json is stale")
    a = ap.parse_args()
    text = build()
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"STALE {OUT.relative_to(ROOT)}: run tools/ui/console_style.py")
            sys.exit(1)
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    d = json.loads(text)
    print(f"{OUT.relative_to(ROOT)}: {len(d['colours'])} colours, {len(d['roles'])} roles, {len(d['icons'])} icons")


if __name__ == "__main__":
    main()
