//! Builds sokol_gfx for `sc-render` and refuses stale shader modules (engine-stack design 4 and 7).
//!
//! sokol is vendored C (third_party/sokol); one translation unit is compiled with the backend for
//! the target. The shader modules in src/shaders/ are generated by tools/sokol_shaders.py from
//! shaders/*.glsl with the pinned sokol-shdc; each records its source's sha256 on its first line,
//! and a module whose source has changed since stops the build, so the Rust and GLSL layouts can
//! never disagree (CLAUDE.md 6.6).

use sha2::{Digest, Sha256};
use std::path::PathBuf;

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let sokol = root.join("../../third_party/sokol");
    let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();
    let debug = std::env::var("PROFILE").map(|p| p == "debug").unwrap_or(false);

    let mut b = cc::Build::new();
    b.file(root.join("csrc/sokol.c")).include(&sokol).warnings(false);
    let gles = matches!(os.as_str(), "linux" | "android" | "emscripten");
    b.define(if gles { "SOKOL_GLES3" } else { "SOKOL_GLCORE" }, None);
    if debug {
        b.define("SOKOL_DEBUG", None);
    }
    b.compile("sokol_gfx");
    match os.as_str() {
        "linux" | "android" => println!("cargo:rustc-link-lib=GLESv2"),
        "macos" => println!("cargo:rustc-link-lib=framework=OpenGL"),
        "windows" => println!("cargo:rustc-link-lib=opengl32"),
        _ => {}
    }
    for f in ["sokol_gfx.h", "sokol_log.h", "gfx.rs", "log.rs"] {
        println!("cargo:rerun-if-changed={}", sokol.join(f).display());
    }
    println!("cargo:rerun-if-changed={}", root.join("csrc/sokol.c").display());

    // Every shader source has a current module.
    let src_dir = root.join("shaders");
    println!("cargo:rerun-if-changed={}", src_dir.display());
    for entry in std::fs::read_dir(&src_dir).expect("shaders/ exists") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("glsl") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path.file_stem().unwrap().to_str().unwrap().to_owned();
        let sha = format!("{:x}", Sha256::digest(std::fs::read(&path).unwrap()));
        let module = root.join("src/shaders").join(format!("{name}.rs"));
        let first = std::fs::read_to_string(&module).ok().and_then(|t| t.lines().next().map(str::to_owned));
        let ok = first.as_deref().is_some_and(|l| l.ends_with(&format!("source sha256 {sha}")));
        assert!(
            ok,
            "sc-render: src/shaders/{name}.rs is missing or stale for shaders/{name}.glsl; run python3 tools/sokol_shaders.py"
        );
    }
}
