"""Generate the exterior preview's lower-deck window patch from the real room outlines.

The design recipe owns selected walls, window stations and furnishing placements. This tool
extends only outboard vertices to the hull service margin, derives portals from those walls,
and validates the resulting layout through the existing layout checker. Runtime is untouched.
Run python tools/exterior_windows.py [--check].
"""
import copy
import json
import math
from pathlib import Path
import sys

from command_suite import patch_layout, run_layout_check
from layout_check import edges, hull_at, outward_normal, inside_poly

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/ships/tern/exterior_windows_design.json"
OUTPUT = ROOT / "data/ships/tern/exterior_windows.json"


def generate():
    """Produce and check one patch; all dimensions are ship-local metres."""
    design = json.loads(SOURCE.read_text())
    layout = json.loads((ROOT / "data/ships/tern/layout.json").read_text())
    suite = json.loads((ROOT / "data/ships/tern/command_suite.json").read_text())
    patch_layout(layout, suite)
    sections = layout["hull"]["sections"]
    patch = {"schema": "starcrew.layout-patch/1", "status": "Exterior art preview. Generated by tools/exterior_windows.py from exterior_windows_design.json; not applied to runtime."}
    patch.update({k: [] for k in ("compartments", "portals", "stations", "fixtures", "fixtures_removed", "systems")})
    patch["furnishings"] = design["furnishings"]
    for spec in design["rooms"]:
        room = copy.deepcopy(next(c for c in layout["compartments"] if c["id"] == spec["room"]))
        threshold = spec["outboard_from_x_m"]
        for brush in room["brushes"]:
            points = []
            for a, b in edges(brush["poly"]):
                points.append(a)
                if abs(a[0]) > threshold and abs(b[0]) > threshold:
                    stations = sorted(s["z_m"] for s in sections if min(a[1], b[1]) < s["z_m"] < max(a[1], b[1]))
                    if b[1] < a[1]: stations.reverse()
                    for z in stations:
                        t = (z-a[1])/(b[1]-a[1])
                        points.append([a[0]+t*(b[0]-a[0]), z])
            poly = []
            for x, z in points:
                if abs(x) > threshold:
                    x = math.copysign(hull_at(sections, z)["half_beam_m"] - design["clearance_m"], x)
                poly.append([round(x, 6), z])
            # Extending a chamfer can leave redundant collinear corners.
            brush["poly"] = [b for i, b in enumerate(poly) if abs((b[0]-poly[i-1][0])*(poly[(i+1)%len(poly)][1]-b[1]) - (b[1]-poly[i-1][1])*(poly[(i+1)%len(poly)][0]-b[0])) > 0.000001]
        patch["compartments"].append(room)
        for i, z in enumerate(spec["window_z_m"]):
            candidates = []
            for brush in room["brushes"]:
                for a, b in edges(brush["poly"]):
                    if min(a[1], b[1]) < z < max(a[1], b[1]):
                        n = outward_normal(a, b)
                        x = a[0] + (z-a[1])*(b[0]-a[0])/(b[1]-a[1])
                        if abs(n[0]) > .9 and abs(x) > threshold:
                            candidates.append((abs(x), x, n))
            assert candidates, f"{room['id']}: no outboard wall at {z} m"
            _, x, n = max(candidates)
            patch["portals"].append({"id": f"p_{room['id']}_window_{i+1}", "kind": "window", "between": [room["id"], "space"],
                                     "center_m": [round(x,6), spec["window_y_m"], z], "normal": [round(n[0],8), 0, round(n[1],8)],
                                     "size_m": spec["size_m"], "max_depth_m": design["max_depth_m"], "bake_only_lods": True})
    patch_layout(layout, patch)
    ok, report = run_layout_check(layout)
    assert ok, report
    # Check actual prop bounds at the authored transforms, not guessed footprint sizes.
    manifests = {s: json.loads((ROOT / f"assets/models/{s}/props.json").read_text())["props"] for s in ("bridge", "suite")}
    for f in patch["furnishings"]:
        bounds = manifests[f["set"]][f["prop"]]["bounds_m"]
        room = next(c for c in layout["compartments"] if c["id"] == f["room"])
        angle = math.radians(f["yaw_deg"]); sn, cs = math.sin(angle), math.cos(angle)
        for x in (bounds["min"][0], bounds["max"][0]):
            for z in (bounds["min"][2], bounds["max"][2]):
                px, pz = f["back_m"][0]+x*cs+z*sn, f["back_m"][2]-x*sn+z*cs
                assert any(inside_poly(b["poly"],px,pz,.012) for b in room["brushes"]), f"{f['room']}: {f['prop']} leaves room"
        assert min(b["y"][0] for b in room["brushes"]) <= f["back_m"][1] + bounds["min"][1] + .012
        assert f["back_m"][1]+bounds["max"][1] <= max(b["y"][1] for b in room["brushes"])
    return patch


if __name__ == "__main__":
    patch = generate()
    text = json.dumps(patch, indent=2) + "\n"
    if "--check" in sys.argv:
        assert OUTPUT.read_text() == text, f"Stale generated patch: {OUTPUT}"
    else:
        OUTPUT.write_text(text, encoding="utf-8")
    print(f"Exterior window patch: {len(patch['portals'])} windows, {len(patch['compartments'])} rooms, {len(patch['furnishings'])} furnishings; layout and prop bounds pass")
