#!/usr/bin/env python3
"""Compile the renderer's shaders with sokol-shdc, at its pinned revision, into committed Rust modules.

Each program is one source in sokol-shdc's dialect under crates/sc-render/shaders/<name>.glsl. This
tool compiles it to GLSL ES 3.00 (the Pi 5, Linux desktops, the browser) and GLSL 4.10 (Windows,
macOS) with the Rust uniform structs and reflection generated (-f sokol_rust), and writes
crates/sc-render/src/shaders/<name>.rs. The first line of each output names the shdc revision and
the sha256 of its source, so --check (and sc-render's build script) can tell a stale module from a
current one without the compiler (openspec/changes/engine-stack, design sections 4 and 7: the Rust
and GLSL layouts come from one source and cannot disagree).

Why the outputs are committed: the compiler is an 11.6 MB binary a platform, too big to commit, and
a Pi building the game offline must not need the network. So the binary is fetched here at its
pinned revision and checked against its sha256 (third_party/sokol/PROVENANCE.md), and the build
uses the committed modules, refusing any whose source changed since it was generated.

Usage: python3 tools/sokol_shaders.py [--check]   (standard library only)
"""

import glob
import hashlib
import os
import platform
import re
import stat
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "crates", "sc-render", "shaders")
OUT = os.path.join(ROOT, "crates", "sc-render", "src", "shaders")
BIN_DIR = os.path.join(ROOT, "third_party", "sokol-shdc")
REV = "11d0cf6"
BINARIES = {  # platform -> (path in sokol-tools-bin, sha256); third_party/sokol/PROVENANCE.md
    ("Linux", "x86_64"): ("bin/linux/sokol-shdc", "ed35e89ef381d521a499096ed4ada85e4d135d8011e151cca6b7d893c43b21df"),
    ("Linux", "aarch64"): ("bin/linux_arm64/sokol-shdc", "446b4bcea0c81d3ae529bc0d93533ea661b017f5b9ec2b2293a4c85f5fdcb639"),
}
SLANG = "glsl300es:glsl410"
STAMP = re.compile(r"^// sokol-shdc ([0-9a-f]+) source sha256 ([0-9a-f]{64})$")


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def shdc():
    """The pinned sokol-shdc for this machine, fetched once and checked against its sha256."""
    key = (platform.system(), platform.machine())
    if key not in BINARIES:
        sys.exit(f"sokol_shaders: no pinned sokol-shdc for {key}; add it to BINARIES and PROVENANCE.md")
    rel, want = BINARIES[key]
    path = os.path.join(BIN_DIR, REV, rel.replace("/", "_"))
    if not os.path.exists(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        url = f"https://raw.githubusercontent.com/floooh/sokol-tools-bin/{REV}/{rel}"
        print(f"fetching {url}")
        urllib.request.urlretrieve(url, path + ".part")
        os.replace(path + ".part", path)
    got = sha256(path)
    if got != want:
        os.remove(path)
        sys.exit(f"sokol_shaders: {rel} at {REV} has sha256 {got}, expected {want}; removed it")
    os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR)
    return path


def stamp_of(rs_path):
    """The (revision, source sha256) a generated module records, or None."""
    if not os.path.exists(rs_path):
        return None
    with open(rs_path, encoding="utf-8") as f:
        m = STAMP.match(f.readline().rstrip("\n"))
    return (m.group(1), m.group(2)) if m else None


def compile_one(exe, src):
    name = os.path.splitext(os.path.basename(src))[0]
    out = os.path.join(OUT, name + ".rs")
    tmp = out + ".tmp"
    subprocess.run([exe, "-i", src, "-o", tmp, "-l", SLANG, "-f", "sokol_rust", "--reflection", "--no-log-cmdline"],
                   check=True, cwd=ROOT)
    with open(tmp, encoding="utf-8") as f:
        body = f.read()
    os.remove(tmp)
    # The generated module names sokol's crate; ours is vendored as sc_render::gfx.
    body = body.replace("use sokol::gfx as sg;", "use crate::gfx as sg;")
    head = f"// sokol-shdc {REV} source sha256 {sha256(src)}\n// Generated by tools/sokol_shaders.py from crates/sc-render/shaders/{name}.glsl; never edit.\n"
    with open(out, "w", encoding="utf-8") as f:
        f.write(head + body)
    print(f"  {os.path.relpath(out, ROOT)}")


def main(argv):
    sources = sorted(glob.glob(os.path.join(SRC, "*.glsl")))
    if "--check" in argv:
        bad = []
        for src in sources:
            name = os.path.splitext(os.path.basename(src))[0]
            st = stamp_of(os.path.join(OUT, name + ".rs"))
            if st != (REV, sha256(src)):
                bad.append(name)
        if bad:
            print("FAIL stale or missing shader modules: " + ", ".join(bad) + "; run python3 tools/sokol_shaders.py")
            return 1
        print(f"ok: {len(sources)} shader modules current")
        return 0
    os.makedirs(OUT, exist_ok=True)
    exe = shdc()
    for src in sources:
        compile_one(exe, src)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
